name: Build

on:
  pull_request:

jobs:
  test:
    name: Build
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Test
      run: |
        swift build
